FROM python:3.6.3

RUN apt-get update -yqq \
  && apt-get install -yqq --no-install-recommends \
    netcat \
  && apt-get -q clean

RUN mkdir -p /usr/src/app
WORKDIR /usr/src/app

ADD ./requirements.txt /usr/src/app/requirements.txt

RUN pip install -r requirements.txt

ADD ./entrypoint-prod.sh /usr/src/app/entrypoint-prod.sh

ADD . /usr/src/app

CMD ["./entrypoint-prod.sh"]
